project: 
  type: website
  output-dir: docs

website:
  title: "Nalany Richardson's Data Analysis Portfolio"
  navbar:
    left:
      - text: "About Me"
        file: aboutme.qmd
      - text: "Projects"
        menu:
          - text: "Starter Analysis Exercise"
            file: starter-analysis-exercise/starter-analysis-exercise.qmd
          - text: "READy Exercise"
            file: ready-exercise/ready-exercise.html
          - text: "Synthetic Data Exercise"
            file: synthetic-analysis/synthetic-analysis.qmd
    right:
      - icon: github 
        href: https://github.com/nalany02/NalanyRichardson-portfolio
format:
  html:
    theme: united
    highlight: zenburn
    css: styles.css
    toc: FALSE